### ISSUE TITLE
ResourcePicker Breaks When Providing initialSelectionIds

### ISSUE THREAD

**Issue by mwood23** [Shopify/shopify-app-bridge#225]
## Describe the bug

When I add `initialSelectionIds` to the ResourcePicker and click add I get a breaking error.

### To Reproduce

Steps to reproduce the behaviour:

1. Launch the app from an embedded app
```jsx
<ResourcePicker
  open={resourcePickerActive}
  selectMultiple={true}
  resourceType="Product"
  showDraftBadge={true}
  showArchivedBadge={true}
  showVariants={true}
  initialSelectionIds={[
    {
      id: "gid://shopify/Product/845496991772",
      variants: [
        { id: "gid://shopify/ProductVariant/45842547671324" },
      ],
    },
  ]}
/>
```
3. Activate the picker
4. Click `Add`

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'variants')
    at AppBridgeResourcePicker-36e9b06c9fb6abd5.js:1:38795
    at Array.forEach (<anonymous>)
    at U.fetchProductDetails (AppBridgeResourcePicker-36e9b06c9fb6abd5.js:1:38741)
    at async AppBridgeResourcePicker-36e9b06c9fb6abd5.js:1:37252
```

### Expected behaviour

Calls `onSelection` with newly updated selection or the initial selection if nothing is changed. 

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- "@shopify/app-bridge": "3.7.9",
- "@shopify/app-bridge-react": "3.7.9",

## Platform

- OS: MacOS
- OS Version: [for example 10.15.5]
- App: Shopify embedded

### Additional context

It breaks the page and users have to refresh unforunately.

**Comment by Sabarinath15** [comment]
I have been experiencing this issue recently. Even without the variants, the page displays a 500 error.
