### ISSUE TITLE
Issue with Modal: Only Loader Visible, Content Not Displaying

### ISSUE THREAD

**Issue by sunnyvaniya21** [Shopify/shopify-app-bridge#396]
## Describe the bug

Hi guys,I'm facing an issue when trying to open a modal. In the modal's section, I only see a loader, and it doesn't show any content.

### To Reproduce

Steps to reproduce the behaviour:

1. Just Open an Modal

### Expected behaviour

While click on open modal button it's show the content of modal in modal's section.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- `@shopify/app-bridge` @ `3.7.10`
- `@shopify/app-bridge-react` @ `4.1.3`
- `@shopify/polaris` @ `12.27.0`

## Platform

- OS: [Windows]
- OS Version: [10]
- App: [Chrome]

### Additional context

![modal_loader](https://github.com/Shopify/shopify-app-bridge/assets/149780278/d7738a2b-4da5-4bbf-bc3e-f7fc1cc52aa2)

**Comment by sunnyvaniya21** [comment]
![image](https://github.com/Shopify/shopify-app-bridge/assets/149780278/261f6e02-91fd-465a-b347-f3484aaf4df8)

**Comment by charlesdobson** [comment]
I'm not able to reproduce with the example you provided. Could you try out a few things for me?

1. Make sure you're in a new browser session (i.e. reload in a new tab).
2. Provide any extra info of your setup (frameworks, etc) that you think might be relevant.
3. Provide a development store that I can see the behaviour on (feel free to ping me on the Partners Slack if you'd prefer!)

**Comment by YaTree** [comment]
Hello all.

I have a similar issue, but it happens only in a specific scenario:
1. Login to the partner account 
2. go to "stores"
3. Login into any of the stores with the app
4. Search for the app and open it
5. Do the magic to open a modal window.

The result - is endless loading, I found that there is this log in the console:
`Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin 'https://' in a call to 'postMessage'.
    at e (https://cdn.shopify.com/shopifycloud/app-bridge.js:1:47579)
    at https://cdn.shopify.com/shopifycloud/app-bridge.js:1:48632`

If I refresh the page and repeat steps 4 and 5 my modal window works as expected.
Please note: that my application passed review, so it means that my app-bridge was setup correctly, I don't know what I should add to the configuration and where to resolve it, just hope that my customers do not face the issue because they log in to the admin console differently.

@charlesdobson Is this input helpful?

**Comment by VladIliukhaAleannLab** [comment]
> Hello all.
> 
> I have a similar issue, but it happens only in a specific scenario:
> 
> 1. Login to the partner account
> 2. go to "stores"
> 3. Login into any of the stores with the app
> 4. Search for the app and open it
> 5. Do the magic to open a modal window.
> 
> The result - is endless loading, I found that there is this log in the console: `Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin 'https://' in a call to 'postMessage'. at e (https://cdn.shopify.com/shopifycloud/app-bridge.js:1:47579) at https://cdn.shopify.com/shopifycloud/app-bridge.js:1:48632`
> 
> If I refresh the page and repeat steps 4 and 5 my modal window works as expected. Please note: that my application passed review, so it means that my app-bridge was setup correctly, I don't know what I should add to the configuration and where to resolve it, just hope that my customers do not face the issue because they log in to the admin console differently.
> 
> [@charlesdobson](https://github.com/charlesdobson) Is this input helpful?

it helped me :)
I investigated the cause of this error, it turned out that during the first initiation, there was no host value in the config (for the shopify-app-bridge script), which are necessary to form parameters to check origin
after which I added as hot fix
              <meta name="shopify-host" content={host ?? ""} />
before initiating the shopify-app-bridge script in the _document.tsx file (I'm using Next.js)
bc I thought that this config was formed from meta-tags (here I guessed)
and that solved the problem (for now)

**Comment by YaTree** [comment]
Unfortunately, it only fixed the exception, I don't receive it anymore with the provided host, but the Modal component still does not work. Without refreshing the page - I see only endless loading.

I rechecked, nothing. no logs. no indication...

**Comment by pama1999** [comment]
I could resolve the issue by manually synchronizing my device clock in the Windows date and time settings. This problem occurs every other week again. Hope this might help someone.

![Image](https://github.com/user-attachments/assets/5e90242d-4d71-462e-aa2f-8c7124b6ee0a)

**Comment by adarsh-27** [comment]
> Set the host parameter in the app bridge settings worked for me, I will let here my setup in case anyone else need. I use rails and set session[:host_parameter] manually in the controller.
> 
> ```
>  <script>
>     sessionStorage.setItem("app-bridge-config", JSON.stringify({
>       apiKey: "<%= ShopifyApp.configuration.api_key %>",
>       shop: "<%= @shop.shopify_domain %>",
>       host: "<%= session[:host_parameter] %>",
>       experimentalFeatures: ["webVitals"],
>       debug: {
>         webVitals: true
>       }
>     }));
>   </script>
>   <script src="https://cdn.shopify.com/shopifycloud/app-bridge.js"></script>
> ```


Where we can place the above code ?

**Comment by meetCrawlapps** [comment]
hey @charlesdobson  is there any update on this ?
