### ISSUE TITLE
Resource picker is not working on some stores

### ISSUE THREAD

**Issue by gulam-quinn** [Shopify/shopify-app-bridge#422]
ResourcePicker fails to open with an error only on some stores, Working fine on others. There is no meaningful error to debug what's happening. Everything else related to app-bridge like Modal etc are working fine.

```
Error: ResourcePicker error
    at app-bridge.js:1:32572
    at app-bridge.js:1:45328
    at app-bridge.js:1:44812
```

This is what i'm passing to  `resourcePicker`
```javascript
const selected = await shopify.resourcePicker({
  type: "product",
  multiple: true,
  filter: {
    hidden: false,
    variants: false,
    draft: false,
    archived: false,
  },
  selectionIds: [],
});

```

Package version
- "@shopify/app-bridge-react": "^4.1.3",
- "@remix-run/react": "^2.7.1",
-  "@shopify/shopify-app-remix": "^3.0.0",

Let me know if more information is required.

**Comment by diemah77** [comment]
Same here!

**Comment by henrytao-me** [comment]
May I know the store and the user having issue please?

**Comment by diemah77** [comment]
Yes, [this one](https://shellyparts.de/) for example.

**Comment by henrytao-me** [comment]
@diemah77 Can I know which app I can test it?

**Comment by diemah77** [comment]
Try it with easyDHL. In the app go to Settings -> Rules -> Create rule. The at the bottom select an operator on items and click on edit:



![Image](https://github.com/user-attachments/assets/e12d6c96-6c1b-41c8-ad22-6246056a19b9)

**Comment by diemah77** [comment]
BTW, this is only happening in SOME shops. In others the picker opens and loads products as intended.

**Comment by diemah77** [comment]
Update: by checking different shops I believe it's a permission issue. If the user does not have the right to access/read the products the resource picker won't load. Can you confirm?

**Comment by gulam-quinn** [comment]
Yes, store has the permission to read products, since we are able to load products for our external dashboard (used by our team internally and i also made a graphQl request to fetch products using store access token and it worked fine. ) but the ResourcePicker fails to load. We even asked store to uninstall and reinstall the app but the issues still exists.

**Comment by lmtNoLimit** [comment]
@henrytao-me I believe I’ve identified the cause of the issue. The staff with access to the store don’t have permission to view products, even though the app has the `write_products` scope. As a result, when the staff uses the app, they are unable to open the ResourcePicker because of this missing permission. To resolve the issue, the staff needs product access permissions, which must be granted by the Account Owner. However, I think this may be unnecessary since the app itself already has the required permissions. I recommend reviewing and addressing this
